package wallet

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"strings"
	"unicode"

	"golang.org/x/crypto/pbkdf2"
)

const (
	// AES key length for AES-256-GCM
	aesKeySize = 32
	// PBKDF2 iterations (NIST recommendation 2024: ≥310000 for SHA-256)
	pbkdf2Iterations = 310000
	// Salt length for PBKDF2
	saltSize = 32
	// BIP-39 English wordlist length
	bip39WordCount = 2048
)

// DeriveKey uses PBKDF2-SHA256 to derive a 256-bit key from a passphrase and salt.
// The salt is generated by the caller (store it alongside the ciphertext).
func DeriveKey(passphrase string, salt []byte) ([]byte, error) {
	if passphrase == "" {
		return nil, errors.New("passphrase must not be empty")
	}
	if len(salt) < 16 {
		return nil, errors.New("salt must be at least 16 bytes")
	}
	key := pbkdf2.Key([]byte(passphrase), salt, pbkdf2Iterations, aesKeySize, sha256.New)
	return key, nil
}

// GenerateSalt returns a cryptographically random salt of saltSize bytes.
func GenerateSalt() ([]byte, error) {
	salt := make([]byte, saltSize)
	if _, err := io.ReadFull(rand.Reader, salt); err != nil {
		return nil, fmt.Errorf("failed to generate salt: %w", err)
	}
	return salt, nil
}

// EncryptAES256GCM encrypts plaintext with AES-256-GCM using the provided key.
// Returns: nonce (12 bytes) || ciphertext || tag — all hex-encoded.
func EncryptAES256GCM(key, plaintext []byte) (string, error) {
	if len(key) != aesKeySize {
		return "", fmt.Errorf("key must be exactly %d bytes", aesKeySize)
	}

	block, err := aes.NewCipher(key)
	if err != nil {
		return "", fmt.Errorf("create cipher: %w", err)
	}

	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return "", fmt.Errorf("create GCM: %w", err)
	}

	nonce := make([]byte, gcm.NonceSize())
	if _, err := io.ReadFull(rand.Reader, nonce); err != nil {
		return "", fmt.Errorf("generate nonce: %w", err)
	}

	// Seal appends tag to ciphertext: nonce || ciphertext+tag
	ciphertext := gcm.Seal(nonce, nonce, plaintext, nil)
	return hex.EncodeToString(ciphertext), nil
}

// DecryptAES256GCM reverses EncryptAES256GCM.
func DecryptAES256GCM(key []byte, hexCiphertext string) ([]byte, error) {
	if len(key) != aesKeySize {
		return nil, fmt.Errorf("key must be exactly %d bytes", aesKeySize)
	}

	data, err := hex.DecodeString(hexCiphertext)
	if err != nil {
		return nil, fmt.Errorf("decode hex ciphertext: %w", err)
	}

	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, fmt.Errorf("create cipher: %w", err)
	}

	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return nil, fmt.Errorf("create GCM: %w", err)
	}

	nonceSize := gcm.NonceSize()
	if len(data) < nonceSize {
		return nil, errors.New("ciphertext too short")
	}

	nonce, ciphertext := data[:nonceSize], data[nonceSize:]
	plaintext, err := gcm.Open(nil, nonce, ciphertext, nil)
	if err != nil {
		return nil, fmt.Errorf("decrypt: %w (authentication failed)")
	}
	return plaintext, nil
}

// ValidateBIP39Mnemonic checks that a space-separated mnemonic has a valid word count
// (12, 15, 18, 21, or 24 words) and that each word is a valid-looking BIP-39 word
// (letters only, lowercase, 3–8 characters — full wordlist check requires embedding the list).
func ValidateBIP39Mnemonic(mnemonic string) error {
	words := strings.Fields(strings.ToLower(strings.TrimSpace(mnemonic)))

	validCounts := map[int]bool{12: true, 15: true, 18: true, 21: true, 24: true}
	if !validCounts[len(words)] {
		return fmt.Errorf("mnemonic must have 12, 15, 18, 21, or 24 words; got %d", len(words))
	}

	for i, word := range words {
		if len(word) < 3 || len(word) > 8 {
			return fmt.Errorf("word %d (%q) length out of BIP-39 range [3..8]", i+1, word)
		}
		for _, ch := range word {
			if !unicode.IsLetter(ch) {
				return fmt.Errorf("word %d (%q) contains non-letter character %q", i+1, word, ch)
			}
		}
	}
	return nil
}

// MnemonicToSeed converts a BIP-39 mnemonic to a 64-byte seed using PBKDF2-SHA512.
// passphrase is the optional BIP-39 salt extension (often "").
func MnemonicToSeed(mnemonic, passphrase string) ([]byte, error) {
	if err := ValidateBIP39Mnemonic(mnemonic); err != nil {
		return nil, err
	}
	// BIP-39 spec: PBKDF2(HMAC-SHA512, mnemonic, "mnemonic"+passphrase, 2048, 64)
	salt := []byte("mnemonic" + passphrase)
	seed := pbkdf2.Key([]byte(mnemonic), salt, 2048, 64, sha256.New)
	return seed, nil
}

// EncryptedWallet is the on-disk representation of an encrypted wallet key.
type EncryptedWallet struct {
	Version    int    `json:"version"`    // schema version
	Salt       string `json:"salt"`       // hex-encoded PBKDF2 salt
	Ciphertext string `json:"ciphertext"` // hex-encoded AES-256-GCM output
	Algorithm  string `json:"algorithm"`  // "aes-256-gcm"
	KDF        string `json:"kdf"`        // "pbkdf2-sha256"
	Iterations int    `json:"iterations"` // PBKDF2 iterations
}

// SealPrivateKey encrypts a hex-encoded private key with the given passphrase.
func SealPrivateKey(hexPrivKey, passphrase string) (*EncryptedWallet, error) {
	salt, err := GenerateSalt()
	if err != nil {
		return nil, err
	}

	key, err := DeriveKey(passphrase, salt)
	if err != nil {
		return nil, err
	}

	privKeyBytes, err := hex.DecodeString(strings.TrimPrefix(hexPrivKey, "0x"))
	if err != nil {
		return nil, fmt.Errorf("invalid hex private key: %w", err)
	}

	ciphertext, err := EncryptAES256GCM(key, privKeyBytes)
	if err != nil {
		return nil, err
	}

	return &EncryptedWallet{
		Version:    1,
		Salt:       hex.EncodeToString(salt),
		Ciphertext: ciphertext,
		Algorithm:  "aes-256-gcm",
		KDF:        "pbkdf2-sha256",
		Iterations: pbkdf2Iterations,
	}, nil
}

// OpenPrivateKey decrypts an EncryptedWallet using the given passphrase.
// Returns the private key as a 0x-prefixed hex string.
func OpenPrivateKey(w *EncryptedWallet, passphrase string) (string, error) {
	salt, err := hex.DecodeString(w.Salt)
	if err != nil {
		return "", fmt.Errorf("invalid salt encoding: %w", err)
	}

	key, err := DeriveKey(passphrase, salt)
	if err != nil {
		return "", err
	}

	privKeyBytes, err := DecryptAES256GCM(key, w.Ciphertext)
	if err != nil {
		return "", fmt.Errorf("wrong passphrase or corrupted ciphertext: %w", err)
	}

	return "0x" + hex.EncodeToString(privKeyBytes), nil
}
